### ISSUE TITLE
Final Todos

### ISSUE THREAD

**Issue by EricaThompson** [EricaThompson/dreamers#85]
## Final list
- [ ] Fix issue where the page redirects to login
- [ ] Fix proxy error
- [x] remove logger
- [x] Fix all console warnings
- [x] remove window testing
- [x] super user
- [x] Seed db - Alan
- [x] the like button needs to be above the bottom bar z-index
- [x] have repository link on about page open in new tab 
- [x] spacing on edit profile
- [x] add comma on to edit view of user creation date
- [x] tags aren't showing up in search
- [x] move up search dropdown one pixel
- [x] Fix spacing of like and option ellipsis so that they don't overlap - Josh
- [x] Remove unnecessary commented out code - Josh
- [x] refactor likes - Erica
- [x] make logo font same size as logo - Alan
- [x] add conditional to feed - if they don't follow anyone, show index
- [x] add errors on all pages/forms - user, create/edit dreams, comments, tags
- [x] fix profile view in case users add emojis
- [x] Break long code lines over 80 characters
- [x] fill in all alt attributes for accessibility
- [x] fix delete comment button

- [x] Like on modal view of dreams

- [x] Fix follow function

- [x] Fix follow button conditional

- [x] Fix follow counter

- [x] Fix follow dropdown

- [x] color like heart

- [x] Error handling

- [x] No dots on comments

- [x]  Add padding to top of profile

- [x]  Remove unnecessary commented out code

- [x] Break long code lines over 80 characters

- [x] Fix all console warnings

Frontend Todos:

- [x] fix profile view in case users add emojis
- [x] unlike and show if it's liked
- [x] position absolute on update button
- [x] add followers
- [x] add conditional to feed - if they don't follow anyone, show index
- [x] add errors on all pages/forms - user, create/edit dreams, comments, tags
- [x] sort out ellipses on comments
- [x] double check tag and user page on all size screens
- [x] logo z-index
- [x] add pop-up for followers
- [x] edit nav bar to expand for larger screen
- [x] Fix issue where the page redirects to login
- [x] make logo font same size as logo
- [x] remove window testing

**Comment by joshkohane** [comment]
- [x] add conditional to feed - if they don't follow anyone, show index
- [x] add errors on all pages/forms - user, create/edit dreams, comments, tags
- [x] fix profile view in case users add emojis
- [x] Break long code lines over 80 characters
- [x] fill in all alt attributes for accessibility
- [x] fix delete comment button

- [x] Remove unnecessary commented out code - Josh
- [x] Fix all console warnings - Cindy
- [x] Fix issue where the page redirects to login - Erica
- [x] make logo font same size as logo - Alan
- [x] remove window testing - Josh
- [x] Seed db in code - Alan
- [x] refactor likes - Erica

Suggested: 
- [x] super user

**Comment by EricaThompson** [comment]
Hey, I moved these into the main issue so that I can quickly see the number of todos left without coming into the issue
